# Generated by Django 4.2.5 on 2023-10-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.JSONField(blank=True, default=None, null=True)),
                ('lot', models.JSONField(blank=True, default=None, null=True)),
                ('area', models.JSONField(blank=True, default=None, null=True)),
                ('address', models.JSONField(blank=True, default=None, null=True)),
                ('location', models.JSONField(blank=True, default=None, null=True)),
                ('summary', models.JSONField(blank=True, default=None, null=True)),
                ('utilities', models.JSONField(blank=True, default=None, null=True)),
                ('building', models.JSONField(blank=True, default=None, null=True)),
                ('vintage', models.JSONField(blank=True, default=None, null=True)),
                ('property_on_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
